name: 'CI Builds'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set Java Home
      run: echo "JAVA_HOME is $JAVA_HOME"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew test